language: java

sudo: required
dist: trusty

jdk:
  - openjdk8
  - openjdk11
  - openjdk12

env:
  - TNT_VERSION=1.9
  - TNT_VERSION=1.10
  - TNT_VERSION=2x
  - TNT_VERSION=2.2
  - TNT_VERSION=2.3

stages:
  - checkstyle
  - test

jobs:
  include:
    - stage: checkstyle
      env: []
      jdk: openjdk11
      before_script: skip
      script: mvn checkstyle:check
      after_success: skip

before_script:
  - .travis/travis.pre.sh

script:
  - .travis/travis.build.sh

after_success:
  - .travis/travis.post.sh
