language: java

sudo: required
dist: trusty

stages:
  - checkstyle
  - test

jobs:
  include:
    - stage: checkstyle
      jdk: openjdk11
      before_script: skip
      script: mvn checkstyle:check
      after_success: skip
    - stage: test
      jdk: oraclejdk11
    - stage: test
      jdk: openjdk10
    - stage: test
      jdk: openjdk11

before_script:
  - .travis/travis.pre.sh

script:
  - .travis/travis.build.sh

after_success:
  - .travis/travis.post.sh
