language: java

sudo: required
dist: trusty

jdk:
  - oraclejdk11
  - openjdk10
  - openjdk11

before_script:
  - src/test/travis.pre.sh

script:
  - mvn verify
  - sudo cat /var/log/tarantool/jdk-testing.log
